name: Check code quality via SonarLint

on:
  workflow_call:

jobs:
  sonarlint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: SonarLint for main with Gradle
        run: ./gradlew sonarlintMain
