name: Collect Test Report via Jacoco

on:
  workflow_call:

jobs:
  jacoco:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Collect test report
        run: ./gradlew jacocoTestReport
